### ISSUE TITLE
How do you build it?

### ISSUE THREAD

**Issue by apraditya** [aroc/side-comments#29]
Hi @aroc ,

Just fork this cool library. And I am struggling building it with `gulp`. The current gulpfile even pointing to the wrong `paths.scripts`. Can you explain the way you're building / releasing it? Thanks.

**Comment by solde9** [comment]
@apraditya
Would you be so kind to post the steps to build it?

**Comment by harrisiirak** [comment]
@solde9 This actually quite easy, but as the README doesn't contain any helpful information, it may create some confusion. Probably you already figured the missing step out.

Install component.js:

```bash
npm install -g component
```

In the repository run:

```bash
npm install # Install dev deps
component build # Build component package
gulp 
```
